### ISSUE TITLE
runtime resoluton won't work with composes

### ISSUE THREAD

**Issue by loadingwyn** [gajus/babel-plugin-react-css-modules#113]
jsx
```js
  <div styleName={type === 'article' ? 'article-card' : 'live-card'}>
```
css:
```css
.search {
    width: 650px;
}
.live-card {
    composes: search;
    white-space: nowrap;
    font-size: 14px;
    line-height: 60px;
    color: #666666;
}
```
I get this:
```html
<div class="reprodStyle_live-card_2j7Qr reprodStyle_four-col_2_FEw"></div>
```
The 'search' class doesn't get added, and the 'four-col' which was composed before is still used.

My environment
---

software | version
-- | --
Babel | 6.24.1
node | 8.1.4
Operating System | windows 10

**Comment by Loading-wyn** [comment]
If I reinstall babel-plugin-react-css-modules, everything works fine. But if I change the class which was composed and compile the project again, this problem will happen.

**Comment by richtera** [comment]
I have a similar problem when using composed classes. When the composed classes are in the global space it gets a bit worse and shows "undefined" for those composed classes. So there is a bit of a problem using composed classes. It's trying to resolve classNames after the already resolving.
So for example

```javascript
import "./styles.css"
```

Will cause something like this for a composed class

```css
.example {
  composes: btn from '../global.css'
}
```

The resolved styles might be

```javascript
var styles = {
  'example': 'styles-example-ASDEF btn'
};
```

The output will results in

```javascript
<SomeComponent className="styles-example-ASDEF undefined"/>
```

This is because it can't resolve "btn" inside of the stylesheet context but should be looking it up inside of the composed stylesheet or leave it alone altogether. I.e. leave names it can't resolve.

Not sure how to fix this. I switched to straight react-css-modules till then.
