### ISSUE TITLE
Is `composes` supposed to work?

### ISSUE THREAD

**Issue by bitttttten** [gajus/babel-plugin-react-css-modules#192]
```css
/* PageTitle.css */
.root {
	composes: h2 from '../../theme/type.css';
	color: #147C3F;
	padding: 1.6rem 0;
}
```

```css
/* theme/type.css */
.heading {
	line-height: 1.2em;
	text-align: center;
	font-weight: bold;
	letter-spacing: 0.8px;
	text-transform: uppercase;
}

.h2 {
	composes: heading;
	font-size: 2.4rem;
}
```

My class name is correct: `<h2 class="PageTitle_root theme_h2 theme_heading">Shopping</h2>`. However the CSS is not:
```css
/* theme/type.css */
._2mTJYElVgbS7n2ZX_6poxK{line-height:1.2em;text-align:center;font-weight:700;letter-spacing:.8px;text-transform:uppercase}
.euz7EGBHQkfc-E5dtLq7b{font-size:38.4px;font-size:2.4rem}

/* PageTitle.css */
.PageTitle_root{color:#147c3f;padding:25.6px 0;padding:1.6rem 0}
```

As you can see, the PageTitle CSS is generating the class name correctly, but the theme/type.css file is not. What's up with that?

My config is this:

```js
// Process JS with Babel.
{
	test: /\.(js|jsx|mjs)$/,
	include: paths.appSrc,
	loader: require.resolve('babel-loader'),
	options: {
		// This is a feature of `babel-loader` for webpack (not Babel itself).
		// It enables caching results in ./node_modules/.cache/babel-loader/
		// directory for faster rebuilds.
		cacheDirectory: false,
		plugins: [
			'transform-decorators-legacy',
			'react-loadable/babel',
			['react-css-modules', {
				context: paths.appSrc,
				generateScopedName,
				webpackHotModuleReloading: false,
				attributeNames: {
					activeStyleName: 'activeClassName'
				}
			}]
		]
	},
},
```
