### ISSUE TITLE
Css scope use data attribute not change ClassName

### ISSUE THREAD

**Issue by lqzhgood** [gajus/babel-plugin-react-css-modules#252]
Now. `Css Scope` solve is use different ClassName . Like this

**The original**
``` css
.btn{
     background: red
}
```
```html
<div class="btn">xxx</div>
```

**babel-plugin-react-css-modules**
``` css
.TestApp_App_btn_md5abc{
     background: red
}
```
```html
<div class="TestApp_App_btn_md5abc">xxx</div>
```

But this will make the class name very long and unfavorable for reading.

Use data attribute be better.

**Data attribute**
```css
.btn[data-css-258219ab] {
    background: red
}
```
```html
<div class="btn" data-css-258219ab>xxx</div>
```

And this is more conducive to the global coverage of attributes. Instead of worrying about ClassName for global attributes.
```css
.btn[data-css-258219ab] {
    background: red
}
```
```html
<div class="btn" data-css-258219ab>xxx</div>
```
Global Css coverage scope css
```css
.btn {
    background: red !importent;
}
```
And Some special cases, such as using JS
```javascript
document.querySelector(".btn").classList.remove("otherCssName")
```
