### ISSUE TITLE
how to make a style global 

### ISSUE THREAD

**Issue by craigcosmo** [gajus/babel-plugin-react-css-modules#26]
How would you import a style globally?

I have this file, `global.css`
```css
    .my-btn{color: red}
```
I want to be able to use class `my-btn` in every component in my project. How would you do that?

**Comment by ksrb** [comment]
@craigcosmo try using [`:global`](https://github.com/css-modules/css-modules#usage-with-preprocessors).
```css
:global {
  .my-btn{color: red}
}
```
Also I think it's generally better practice to just ask a question in one place and mention someone if you need help 😃.

**Comment by ksrb** [comment]
The easiest way I can think of doing that is to define that class in a global.**scss** and import it everywhere respectively.

There's also no reason you can't just use that global class verbatim via `classname`.

**Comment by gajus** [comment]
```css
:global .my-btn { color: red }
```
