### ISSUE TITLE
Parse error: Unexpected token

### ISSUE THREAD

**Issue by rico345100** [gajus/babel-plugin-react-css-modules#35]
I'm using browserify + gulp, and just tested with latest version 2.1.1, it fails with:

```
/Users/rico345100/Desktop/learn/browserifyTest/src/app.css:1
.table {
^
ParseError: Unexpected token
```

I just followed your example, it wasn't working at all with browserify + gulp.

This is gulp code:
```javascript
gulp.task('default', () => {
	return browserify({
		entries: ['./src/app.js'],
		debug: true
	})
	.transform(babelify, { 
		presets: ["es2015", "react"],
		plugins: [
			"babel-plugin-react-css-modules",
		]
	})
	.bundle()
	.on('error', swallowError)
	.pipe(source('app.js'))
	.pipe(buffer())
	.pipe(gulp.dest('./build'));
});
```

and these are js codes:

```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import table from './app.css';

class App extends React.Component {
	render() {
		return (
			<div styleName='table.table'>
				<div styleName='table.row'>
					<div styleName='table.cell'>A1</div>
					<div styleName='table.cell'>B1</div>
					<div styleName='table.cell'>C1</div>
				</div>
			</div>
		);
	}
}

ReactDOM.render(
	<App />,
	document.getElementById('entry')
);
```

```css
.table {
	display: table;
}

.row {
	display: table-row;
}

.cell {
	display: table-cell;
	padding: 5px;
}

.cell:nth-child(1) {
	background: #f00;
}

.cell:nth-child(2) {
	background: #0f0;
}

.cell:nth-child(3) {
	background: #00f;
}

.yellow {
	background: #ff0!important;
}
```

Any solution please?
