### ISSUE TITLE
Adding "composes" doesn't update className

### ISSUE THREAD

**Issue by aevk** [gajus/babel-plugin-react-css-modules#48]
Let's say I have this code:
```css
/* styles.css */
.center {
  text-align: center;
}
.block {
  background-color: white;
}
```
```js
/* mycomponent.js */
import "styles.css"

render() {
  return <div styleName="block">
    hello world
  </div>
}
```

The output styles will be something like
```html
...
<div class="styles-block_3XNkZ">...
...
```

Now if I add "composes"
```css
/* styles.css */
.center {
  text-align: center;
}
.block {
  composes: center;
  background-color: white;
}
```
the component class remains the same (only has **styles-block_3XNkZ**). Even if I refresh page (f5) it will not help because webpack output js still has old css name  (like):
```javascript
// webpack output bundle
...
exports.locals = {
  "center": "styles-center_3l7jm",
  "block": "styles-block_3XNkZ"
};
...
```
If I change somehow the component it will trigger the changes, and the component will has the correct classes
```html
...
<div class="styles-block_3XNkZ styles-center_3l7jm">...
...
```
I use

    "webpack": "^2.2.0",
    "webpack-dev-middleware": "^1.9.0",
    "webpack-hot-middleware": "^2.15.0"

    "babel-plugin-react-css-modules": "^2.2.0" (--save)

I tried [https://github.com/gajus/babel-plugin-react-css-modules/tree/master/demo](https://github.com/gajus/babel-plugin-react-css-modules/tree/master/demo), and got the same  
behavior.
